eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: lb://user-management
          predicates:
            -path=/api/users/**

server:
  port: 8762